### ISSUE TITLE
what is the meaning of 5D images, dimension, timepoint for image details?

### ISSUE THREAD

**Issue by semir2** [IDR/idr.openmicroscopy.org#166]
Hi,
    Thanks for your great job, I am instesting in it. Now, I have a problem with the meaning of image details.
![图片](https://user-images.githubusercontent.com/46958122/185538240-c2c22e8d-e1de-4597-8846-4489a4c81baf.png)
what does mean for Z-sections,Timepoints, Dimensions (XY)?

Best

**Comment by sbesson** [comment]
Hi @semir2 you can read more about OME's definition of images as five-dimensional entities in the original [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1175959/).

`Dimensions(XY)` and `Z-sections` define the dimensions of the image alongside the three spatial dimensions (XYZ)
`Timepoints` defines the dimension of the image alongside the time dimension e.g. in the case of a time-lapse acquisition

**Comment by semir2** [comment]
> 

Many thanks

**Comment by sbesson** [comment]
No problem. Closing this issue as resolved.
